### ISSUE TITLE
Circle current day with 𝒪 on month calendar

### ISSUE THREAD

**Issue by craigmayhew** [craigmayhew/pdf-year-planner#2]
## Feature

It would save on cognitive effort to have the current day circled 𝒪 on the mini calendar in the top right of each day page.

**Comment by craigmayhew** [comment]
Initial attempts to get the character 𝒪 to render have failed.

I then tried an svg approach:
```css
div.year_month a div div.circledsingle {
    background-image: url('data:image/svg+xml;utf8,<svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="20.0pt" height="20.0pt" viewBox="0 0 20.0 20.0" preserveAspectRatio="xMidYMid meet"><g transform="translate(0.0,20.0) scale(0.01,-0.01)" fill="#000000" stroke="none"><path d="M1365 1856 c-54 -17 -81 -32 -141 -78 -98 -74 -140 -167 -122 -268 17 -93 17 -93 96 -64 37 14 70 29 75 33 4 4 1 24 -8 44 -19 47 -19 130 1 168 25 50 114 75 167 48 93 -48 129 -141 129 -334 -1 -213 -45 -405 -137 -590 -66 -134 -126 -211 -206 -264 -103 -69 -202 -87 -307 -56 -127 38 -182 150 -182 368 0 316 113 612 303 796 l46 44 -26 38 -25 39 -30 -18 c-96 -56 -239 -203 -306 -316 -49 -80 -108 -222 -133 -318 -31 -117 -38 -318 -15 -421 34 -152 113 -259 234 -315 51 -24 68 -27 167 -27 81 0 125 5 165 19 208 70 400 237 514 447 138 252 185 632 105 845 -31 81 -107 157 -178 178 -64 19 -130 20 -186 2z"/></g></svg>');
    background-position: center; 
    background-repeat: no-repeat;
    height: 4mm;
}
```
That helped me decide I don't like the character 𝒪 as a way of circling the day. A rotated irregular border radius gives a better result:

```css
div.year_month a div div.circled {
    border: 2px solid #000;
    border-radius: 40px 60px 40px 60px;
    -webkit-transform: rotate(-15deg);
}
```
